esphome:
  name: distric-heating

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino

external_components:
  - source:
      type: local
      path: ./components
    components: [uh50_reader]

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret district_heating_api_key

ota:
  - platform: esphome
    password: !secret district_heating_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  - id: uart_in
    rx_pin: GPIO16
    baud_rate: 2400
    data_bits: 7
    parity: EVEN
    stop_bits: 2
    rx_buffer_size: 2048
  - id: uart_out
    tx_pin: GPIO17
    baud_rate: 300
    data_bits: 7
    parity: EVEN
    stop_bits: 2

one_wire:
  - platform: gpio
    pin: GPIO25

sensor:
  - platform: dallas_temp
    address: 0xe00000005927f228
    name: "Hot Water Temperature"
    update_interval: 30s
  - platform: dallas_temp
    address: 0x100000005add1f28
    name: "Cold Water Temperature"
    update_interval: 30s

  - platform: uh50_reader
    id: uh50_reader_component
    uart_in_id: uart_in
    uart_out_id: uart_out
    update_interval: 1min
    read_button:
      name: "Read Meter Now"
    cumulative_active_import:
      name: "Cumulative Active Import"
      id: "uh50_cumulative_active_import"
      unit_of_measurement: MWh
      accuracy_decimals: 3
      state_class: "total_increasing"
      device_class: "energy"
    cumulative_volume:
      name: "Cumulative Volume"
      id: "uh50_cumulative_volume"
      unit_of_measurement: m3
      accuracy_decimals: 3
      state_class: "total_increasing"
      device_class: "energy"
    current_power:
      name: "Current Power"
      id: "uh50_current_power"
      unit_of_measurement: kW
      accuracy_decimals: 2
      state_class: "measurement"
      device_class: "energy"
    flow_rate:
      name: "Flow Rate"
      id: "uh50_flow_rate"
      unit_of_measurement: m3ph
      accuracy_decimals: 3
      state_class: "measurement"
      device_class: "energy"
    temperature_flow:
      name: "Flow Temperature"
      id: "uh50_flow_temperature"
      unit_of_measurement: C
      accuracy_decimals: 2
      state_class: "measurement"
      device_class: "temperature"
    temperature_return:
      name: "Return Temperature"
      id: "uh50_return_temperature"
      unit_of_measurement: C
      accuracy_decimals: 2
      state_class: "measurement"
      device_class: "temperature"
    temperature_diff:
      name: "Diff Temperature"
      id: "uh50_diff_temperature"
      unit_of_measurement: C
      accuracy_decimals: 2
      state_class: "measurement"
      device_class: "temperature"
